version: '3.8'
services:
  web:
    build: .
    container_name: django-app-test
    volumes :
      - static:/home/user/src/app/static
      - media:/home/user/src/app/media
    ports:
      - "127.0.0.1:8000:8000"
#    env_file:
#      - ./.env
    command: python manage.py runserver
volumes:
    static:
    media: