# Generated by Django 4.2.3 on 2023-07-29 10:22

from django.db import migrations, models
import django.db.models.deletion
import task.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
        ('users', '0004_profile_house'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='users.profile'),
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NC', 'Not Complet'), ('C', 'complet')], default='NC', max_length=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to='users.profile')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='house.house')),
            ],
        ),
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(upload_to=task.models.GenerateAttachementFilePath())),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachement', to='task.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.tasklist'),
            preserve_default=False,
        ),
    ]
