# Generated by Django 4.2.3 on 2023-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_completed_by_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NC', 'Not Complet'), ('C', 'Complet')], default='NC', max_length=2),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.CharField(choices=[('NC', 'Not Complet'), ('C', 'Complet')], default='NC', max_length=2),
        ),
    ]
